Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/nbclient/client.py", line 767, in _async_poll_for_reply
    msg = await ensure_async(self.kc.shell_channel.get_msg(timeout=new_timeout))
  File "/usr/local/lib/python3.10/dist-packages/nbclient/util.py", line 99, in ensure_async
    result = await obj
  File "/usr/local/lib/python3.10/dist-packages/jupyter_client/channels.py", line 315, in get_msg
    raise Empty
_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/usr/local/lib/python3.10/dist-packages/nbclient/client.py", line 1256, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/local/lib/python3.10/dist-packages/nbclient/util.py", line 87, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/usr/local/lib/python3.10/dist-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.10/dist-packages/nbclient/client.py", line 694, in async_execute
    await self.async_execute_cell(
  File "/usr/local/lib/python3.10/dist-packages/nbclient/client.py", line 993, in async_execute_cell
    exec_reply = await self.task_poll_for_reply
  File "/usr/local/lib/python3.10/dist-packages/nbclient/client.py", line 791, in _async_poll_for_reply
    error_on_timeout_execute_reply = await self._async_handle_timeout(timeout, cell)
  File "/usr/local/lib/python3.10/dist-packages/nbclient/client.py", line 843, in _async_handle_timeout
    raise CellTimeoutError.error_from_timeout_and_cell(
nbclient.exceptions.CellTimeoutError: A cell timed out while it was being executed, after 30 seconds.
The message was: Cell execution timed out.
Here is a preview of the cell contents:
-------------------
['max_depth = 4', 'd_aic = dict();', 'Q_aic = copy(Q_directed)', 'for level in range(max_depth+1,n_eta+1): # delete levels not used', "    #print(f'{max_depth=} so deleting {level=}')"]
...
['                        Q_aic.delete_edge(vert,nv)', '                    else:', '                        hang+=1', '                if hang==0 and vert != root:', '                    Q_aic.delete_vertex(vert)']
-------------------

